config/routes.rb
Rails.application.routes.draw do
  resources :stations do
    resources :tanks
  end
  resources :retailer_suppliers

  devise_for :users, skip: [:registration]
  devise_for :retailers
  devise_for :suppliers
  devise_for :admins, skip: [:registration]
  get 'retailer_suppliers/pending' => 'retailer_suppliers#pending'
  get 'pages/about'
  get 'pages/contact'
  get 'retailer/transfers' => 'retailers#transfers'
  get 'retailer/inactive_stations' => 'retailers#inactive_stations'
  get 'retailer/dashboard' => 'retailers#dashboard', as: :retailer_dashboard
  get 'admin/dashboard' => 'admins#dashboard', as: :admin_dashboard
  get 'supplier/dashboard' => 'suppliers#dashboard', as: :supplier_dashboard
  get 'retailer/my_stations' => 'retailers#my_stations'
  get 'admin/retailers' => 'admins#retailers'

  root to: 'pages#home'
end

app/models/retailer_supplier.rb
class RetailerSupplier < ActiveRecord::Base
  belongs_to :retailer
  belongs_to :supplier

  enum approval: [:pending, :accept, :decline]

  def approved?
    accept?
  end

  def declined?
    decline?
  end
end

app/controllers/retailer_suppliers_controller.rb
class RetailerSuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_retailer, only: [:create, :index]

  def index
    @connection = @retailer.retailer_suppliers.all
  end

  def new
    @connection = RetailerSupplier.new
  end

  def create
    @connection = RetailerSupplier.new(secure_params)
    @supplier = Supplier.find_by(params[:account_number])
    @connection.supplier = @supplier
    if @connection.save
      redirect_to @connection, notice: "Connection request has been sent to the #{@supplier.first_name} and waiting for their approval" if current_user.retailer?
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def pending
    @connection = @retailer.retailer_suppliers.all.where(approval: 0)
  end

  private

  def secure_params
    params.require(:retailer_supplier).permit(:retailer_id, :supplier_id, :account_number, :message, :approval)
  end

  def set_supplier
  end

  def set_retailer
    @retailer = current_user if current_user.retailer?
  end
end

app/helpers/retailer_suppliers_helper.rb
module RetailerSuppliersHelper
end

app/views/retailer_suppliers/_form.html.erb
<div class='col-sm-7 col-sm-offset-1'>
  <%= simple_form_for(@connection,:html => { :class => "form-horizontal" }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :account_number, label: "Supplier Account#"%>
    <%= f.input :message, label: "Message" %>
    <%= f.association :retailer, :as => :hidden if current_user.retailer?%>
    <%= f.association :supplier, :as => :hidden if current_user.supplier?%>
  </div>

  <div class="form-actions">
    <%= f.button :submit,"Send Request", class: "btn btn-primary" %>
  </div>
  <% end %>
  <%= link_to 'Back', stations_path %>
</div>

app/views/retailer_suppliers/_nav.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <div class='page-header'>
      <h1 class='pull-left'>
        <i class='icon-beer'></i>
        <span>Your suppliers</span>
      </h1>
    </div>
    <div class="dash-tool">
      <div class="btn-group" role="group" id="dash_tool" aria-label="...">
        <button type="button" class="btn btn-default"><%= link_to "All suppliers", retailer_suppliers_path %></button>
        <button type="button" class="btn btn-default"><%= link_to "Pending Requests", retailer_suppliers_pending_path %></button>
        <button type="button" class="btn btn-default"><%= link_to new_retailer_supplier_path do %>
          <i class='icon-plus'></i>
          Add Supplier</span>
        <% end %></button>

    </div>
  </div>
</div>
</div>

app/views/retailer_suppliers/edit.html.erb
<%= render 'nav' %>

app/views/retailer_suppliers/index.html.erb
<%= render 'nav' %>
<div class="row">
  <div class="col-sm-12">
    <div class="box bordered-box blue-border" style="margin-bottom:0;">
      <div class="box-header blue-background">
        <div class="title">All Suppliers</div>
      </div>
      <div class="box-content box-no-padding">
        <div class="responsive-table">
          <div class="scrollable-area">
            <table class="table" style="margin-bottom:0;">
              <thead>
                <tr>
                  <th>
                    Name
                  </th>
                  <th>
                    E-mail
                  </th>
                  <th>
                    Status
                  </th>
                  <th></th>
                </tr>
              </thead>
              <% @connection.each do |connection|%>
              <tbody>
                <tr>
                  <td><%= connection.supplier.first_name + " " + connection.supplier.last_name %></td>
                  <td><%= connection.supplier.email %></td>
                  <td>
                    <% if connection.pending? %>
                    <span class="label label-warning">Pending</span>
                    <%elsif connection.approved?%>
                    <span class="label label-success">Approved</span>
                    <%else%>
                    <span class="label label-danger">Declined</span>
                    <%end%>
                  </td>
                  <td>
                    <div class="text-right">
                      <a class="btn btn-success btn-xs" href="#">
                        <i class="icon-ok"></i>
                      </a>
                      <a class="btn btn-danger btn-xs" href="#">
                        <i class="icon-remove"></i>
                      </a>
                    </div>
                  </td>
                </tr>
              </tbody>
              <%end%>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/retailer_suppliers/new.html.erb
<%= render "nav"%>
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default">
    <div class="panel-body">

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/retailer_suppliers/pending.html.erb
<%= render 'nav' %>
<div class="row">
  <div class="col-sm-12">
    <div class="box bordered-box blue-border" style="margin-bottom:0;">
      <div class="box-header blue-background">
        <div class="title">All Suppliers</div>
      </div>
      <div class="box-content box-no-padding">
        <div class="responsive-table">
          <div class="scrollable-area">
            <% @connection.each do |connection|%>
            <table class="table" style="margin-bottom:0;">
              <thead>
                <tr>
                  <th>
                    Name
                  </th>
                  <th>
                    E-mail
                  </th>
                  <th>
                    Status
                  </th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= connection.supplier.first_name + " " + connection.supplier.last_name %></td>
                  <td><%= connection.supplier.email %></td>
                  <td>
                    <% if connection.pending? %>
                    <span class="label label-warning">Pending</span>
                    <%elsif connection.approved?%>
                    <span class="label label-success">Approved</span>
                    <%else%>
                    <span class="label label-danger">Declined</span>
                    <%end%>
                  </td>
                  <td>
                    <div class="text-right">
                      <a class="btn btn-success btn-xs" href="#">
                        <i class="icon-ok"></i>
                      </a>
                      <a class="btn btn-danger btn-xs" href="#">
                        <i class="icon-remove"></i>
                      </a>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/retailer_suppliers/show.html.erb
<%= render 'nav' %>