config/routes.rb
Rails.application.routes.draw do
  resources :stations do
    resources :tanks
  end
  resources :retailer_suppliers

  devise_for :users, skip: [:registration]
  devise_for :retailers
  devise_for :suppliers
  devise_for :admins, skip: [:registration]
  get 'retailer_suppliers/pending' => 'retailer_suppliers#pending'
  get 'pages/about'
  get 'pages/contact'
  get 'retailer/transfers' => 'retailers#transfers'
  get 'retailer/inactive_stations' => 'retailers#inactive_stations'
  get 'retailer/dashboard' => 'retailers#dashboard', as: :retailer_dashboard
  get 'admin/dashboard' => 'admins#dashboard', as: :admin_dashboard
  get 'supplier/dashboard' => 'suppliers#dashboard', as: :supplier_dashboard
  get 'retailer/my_stations' => 'retailers#my_stations'
  get 'admin/retailers' => 'admins#retailers'

  root to: 'pages#home'
end

app/models/station.rb
class Station < ActiveRecord::Base
  belongs_to :retailer, class_name: 'User'
  has_many :tanks, dependent: :destroy
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)
    @station.retailer = current_user

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_station
    @station = Station.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def station_params
    params.require(:station).permit(:brand, :business_name, :tax_id, :phone_number, :contact_person, :cell_number, :address1, :address2, :city, :state, :zip, :station_reg_number, :retailer_id)
  end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<div class='col-sm-7 col-sm-offset-1'>
  <%= simple_form_for(@station,:html => { :class => "form-horizontal" }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :brand, label: "Brand",:collection => fuel_brands, :selected => "Exxon"%>
    <%= f.input :business_name, label: "Business Name" %>
    <%= f.input :tax_id , label: "Tax ID"%>
    <%= f.input :phone_number, label: "Phone Number" %>
    <%= f.input :contact_person, label: "Contact Person" %>
    <%= f.input :cell_number, label: "Cell Number of contact person" %>
    <%= f.input :address1, label: "Address" %>
    <%= f.input :address2, label: "Address" %>
    <%= f.input :city, label: "City" %>
    <%= f.input :state, :label => "State", :collection => us_states, :selected => "New Jersey"%>
    <%= f.input :zip, label: "Zip code"%>
    <%= f.input :station_reg_number, label: "Station Registration #" %>
    <%= f.association :retailer, :as => :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
  <% end %>
  <%= link_to 'Back', stations_path %>
</div>

app/views/stations/_tank_form.html.erb
<div class='col-sm-7 col-sm-offset-1'>
  <h2>Add a Tank</h2>
  <%= simple_form_for([@station, @station.tanks.build],:html => { :class => "form-horizontal" }) do |f| %>
  <div class="form-inputs">
    <%= f.input :type_of_fuel, label: "Fuel Type",:collection => fuel_type, :selected => "Regular"%>
    <%= f.input :size, label: "Size" %>
    <%= f.input :registration_id, label: "Tank Registration ID"%>
    <%= f.association :station, :as => :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %>
|
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stations</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Business name</th>
      <th>Tax</th>
      <th>Phone number</th>
      <th>Contact person</th>
      <th>Cell number</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Station reg number</th>
      <th>Retailer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
    <tr>
      <td><%= station.brand %></td>
      <td><%= station.business_name %></td>
      <td><%= station.tax_id %></td>
      <td><%= station.phone_number %></td>
      <td><%= station.contact_person %></td>
      <td><%= station.cell_number %></td>
      <td><%= station.address1 %></td>
      <td><%= station.address2 %></td>
      <td><%= station.city %></td>
      <td><%= station.state %></td>
      <td><%= station.zip %></td>
      <td><%= station.station_reg_number %></td>
      <td><%= station.retailer %></td>
      <td><%= link_to 'Show', station %></td>
      <td><%= link_to 'Edit', edit_station_path(station) %></td>
      <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<%= render "retailers/my_stations"%>
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default">
    <div class="panel-body">

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/stations/show.html.erb
<%= render "retailers/my_stations"%>

<div class="jumbotron">
  <p id="notice"><%= notice %></p>
  <div class="row invoice">
    <div class="col-sm-12">
      <div class="box">
        <div class="box-content box-double-padding">
          <div class="row">
            <div class="invoice-header">
              <div class="invoice-title">
                <%=@station.brand%>
                <%= link_to edit_station_path(@station) do %>
                <i class="icon-wrench"></i>
                <%end%>
              </div>
              <div class="invoice-number">
                <span class="invoice-name"><%= @station.business_name%></span>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4 seller">
              <div class="lead text-contrast">Details</div>
              <i class="icon-globe"></i>
              <address>
                <strong>Brand:</strong>
                <strong><%= @station.brand %></strong>
                <br>
                <strong>No. of tanks:</strong>
                <%=@station.tanks.all.count%>
                <br>
                <strong>DBA:</strong>
                <%= @station.business_name %>
                <br>
                <strong>Tax ID:</strong>
                <%= @station.tax_id %>
                <br>
                <br>
                <strong>Contact Person:</strong>
                <small><%= @station.contact_person %></small>
                <br>
                <small><%= @station.cell_number %></small>
              </address>
            </div>
            <div class="col-sm-4 buyer">
              <div class="lead text-contrast"></div>
              <i class="icon-globe"></i>
              <address>
                <strong>Current Owner:</strong>
                <strong><%= @station.retailer.first_name + " " + @station.retailer.last_name %></strong>
                <br>
                <strong>Store Phone:
                </strong><%= @station.phone_number %>
                <br>
                <strong>Address:</strong><%= @station.address1 %>
                <br>
                <strong>city:</strong><%= @station.city %>
                <br>
                <strong>State:</strong><%= @station.state %>
                <br>
                <small>
                  <a href="mailto:jane@doe.com">jane@doe.com</a>
                </small>
                <br>
                <strong>Registration No.</strong>
                <small><%= @station.station_reg_number%></small>
              </address>
            </div>
            <div class="col-sm-4 info">
              <div class="lead text-muted">Info</div>
              Created at:
              <strong><%= @station.created_at.strftime("%d %b. %Y")%></strong>
              <br>
              Updated:
              <strong><%= time_ago_in_words(@station.updated_at) %>
                ago by
                <%= @station.retailer.first_name %></strong>
            </div>
          </div>
          <hr class="hr-drouble">
          <div class="row">
            <div class="col-sm-12">
              <div class="responsive-table">
                <div class="scrollable-area">
                  <table class="table table-striped table-hover table-bordered">
                    <thead>
                      <tr>
                        <th>Order#</th>
                        <th>Fuel Type</th>
                        <th>
                          <div class="text-center">Qty</div>
                        </th>
                        <th>
                          <div class="text-right">Price</div>
                        </th>
                        <th>
                          <div class="text-right">Price total</div>
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>1</td>
                        <td>89</td>
                        <td>
                          <div class="text-center">1</div>
                        </td>
                        <td>
                          <div class="text-right">$302.00</div>
                        </td>
                        <td>
                          <div class="text-right">$302.00</div>
                        </td>
                      </tr>
                      <tr>
                        <td>2</td>
                        <td>95</td>
                        <td>
                          <div class="text-center">4</div>
                        </td>
                        <td>
                          <div class="text-right">$486.00</div>
                        </td>
                        <td>
                          <div class="text-right">$1,944.00</div>
                        </td>
                      </tr>
                      <tr>
                        <td>3</td>
                        <td>99</td>
                        <td>
                          <div class="text-center">1</div>
                        </td>
                        <td>
                          <div class="text-right">$360.00</div>
                        </td>
                        <td>
                          <div class="text-right">$360.00</div>
                        </td>
                      </tr>
                      <tr>
                        <td>4</td>
                        <td>85</td>
                        <td>
                          <div class="text-center">4</div>
                        </td>
                        <td>
                          <div class="text-right">$250.00</div>
                        </td>
                        <td>
                          <div class="text-right">$1,000.00</div>
                        </td>
                      </tr>
                      <tr>
                        <td>5</td>
                        <td>Diesel</td>
                        <td>
                          <div class="text-center">2</div>
                        </td>
                        <td>
                          <div class="text-right">$377.00</div>
                        </td>
                        <td>
                          <div class="text-right">$754.00</div>
                        </td>
                      </tr>
                      <tr>
                        <td>6</td>
                        <td>Diesel</td>
                        <td>
                          <div class="text-center">3</div>
                        </td>
                        <td>
                          <div class="text-right">$107.00</div>
                        </td>
                        <td>
                          <div class="text-right">$321.00</div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <hr class="hr-normal">
          <div class="row">
            <div class="col-sm-12">
              <div class="text-right text-contrast subtotal">
                <div class="btn btn-success">
                  Create New Order
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="well comment">
                Current Order Progress
                <div class="progress">
                  <div class="progress-bar progress-bar-danger" style="width:70%;">
                    <strong>60%</strong>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr class="hr-drouble">
  <div class="row">
    <% count = 1 %>
    <% @station.tanks.each do |i| %>
    <div class="col-sm-6 col-md-3">
      <div class="box">
        <div class="box-header">
          <div class="title">
            <i class="icon-inbox"></i>
            Tank
            <%= count %>
          </div>
          <div class='pull-right'>
            <%= link_to edit_station_tank_path(@station, i) do %>
            <i class="icon-wrench"></i>
            <%end%>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <div class="box-content box-statistic">
              <h3 class="title text-error"><%= i.type_of_fuel %></h3>
              <div class="text-error icon-tint align-right"></div>
            </div>
            <div class="box-content box-statistic">
              <h3 class="title text-warning"><%= i.size %>
                Gallons</h3>
              <div class="text-warning icon-filter align-right"></div>
            </div>
            <div class="box-content box-statistic">
              <small>Registration No.</small>
              <h3 class="title text-primary"><%= i.registration_id %></h3>
              <div class="text-primary icon-edit align-right"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% count += 1 %>
    <% end %>
  </div>

  <%= link_to "Add Tank", new_station_tank_path(@station), class: "btn btn-primary" %>