config/routes.rb
Rails.application.routes.draw do
  resources :stations do
    resources :tanks
  end
  resources :retailer_suppliers

  devise_for :users, skip: [:registration]
  devise_for :retailers
  devise_for :suppliers
  devise_for :admins, skip: [:registration]
  get 'retailer_suppliers/pending' => 'retailer_suppliers#pending'
  get 'pages/about'
  get 'pages/contact'
  get 'retailer/transfers' => 'retailers#transfers'
  get 'retailer/inactive_stations' => 'retailers#inactive_stations'
  get 'retailer/dashboard' => 'retailers#dashboard', as: :retailer_dashboard
  get 'admin/dashboard' => 'admins#dashboard', as: :admin_dashboard
  get 'supplier/dashboard' => 'suppliers#dashboard', as: :supplier_dashboard
  get 'retailer/my_stations' => 'retailers#my_stations'
  get 'admin/retailers' => 'admins#retailers'

  root to: 'pages#home'
end

app/models/retailer.rb
class Retailer < User
  has_many :stations
  has_many :retailer_suppliers
  has_many :suppliers, through: :retailer_suppliers
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @retailer = current_user
  end

  def my_stations
    @stations = current_user.stations.all
  end

  def inactive_stations
  end

  def transfers
  end
end

app/helpers/retailers_helper.rb
module RetailersHelper
  def image_for(station)
    case station.brand
    when 'Amoco'
      image_tag('amoco.jpg', height: '230', width: '230')
    when 'ARCO'
      image_tag('arco.jpg', height: '230', width: '230')
    when 'BP'
      image_tag('bp.jpg', height: '230', width: '230')
    when 'Chevron'
      image_tag('chevron.jpeg', height: '230', width: '230')
    when 'Circle K'
      image_tag('circlek.gif', height: '230', width: '230')
    when 'Citgo'
      image_tag('citgo.jpg', height: '230', width: '230')
    when 'Clark Brands'
      image_tag('clark.jpg', height: '230', width: '230')
    when 'Costco'
      image_tag('costco.jpg', height: '230', width: '230')
    when 'Cumberland Farms'
      image_tag('cumberland.jpg', height: '230', width: '230')
    when 'Exxon'
      image_tag('exxon.png', height: '230', width: '230')
    when 'Flying J'
      image_tag('FLYING_J.jpg', height: '230', width: '230')
    when 'Gas City, Ltd.'
      image_tag('default.jpg', height: '230', width: '230')
    when 'Getty'
      image_tag('getty.jpg', height: '230', width: '230')
    when 'Go-Mar'
      image_tag('default.jpg', height: '230', width: '230')
    when 'Gulf'
      image_tag('gulf.jpg', height: '230', width: '230')
    when 'Hess'
      image_tag('hess.jpg', height: '230', width: '230')
    when 'High\'s Dairy Stores'
      image_tag('highs.jpeg', height: '230', width: '230')
    when 'Holiday'
      image_tag('holiday.jpg', height: '230', width: '230')
    when 'Irving Oil'
      image_tag('irving.png', height: '230', width: '230')
    when 'Kroger brand gasoline'
      image_tag('kroger.png', height: '230', width: '230')
    when 'Kum & Go'
      image_tag('kum.gif', height: '230', width: '230')
    when 'Kwik Trip'
      image_tag('kwiktrip.jpg', height: '230', width: '230')
    when 'Love\'s'
      image_tag('loves.jpg', height: '230', width: '230')
    when 'Marathon Oil'
      image_tag('marathon.png', height: '230', width: '230')
    when 'Lukoil'
      image_tag('lukoil.png', height: '230', width: '230')
    when 'Mobil'
      image_tag('mobil.png', height: '230', width: '230')
    when 'Murphy USA'
      image_tag('murphy.png', height: '230', width: '230')
    when 'Phillips 66'
      image_tag('phillips66.jpg', height: '230', width: '230')
    when 'Pilot'
      image_tag('pilot.jpg', height: '230', width: '230')
    when 'QuickChek'
      image_tag('quickchek.png', height: '230', width: '230')
    when 'QuikTrip'
      image_tag('quicktrip.jpg', height: '230', width: '230')
    when 'RaceTrac/Raceway'
      image_tag('racetrac.jpg', height: '230', width: '230')
    when 'Shell'
      image_tag('shell.png', height: '230', width: '230')
    when 'Royal Farms'
      image_tag('royalfarms.png', height: '230', width: '230')
    when 'Rutter\'s Farm Stores'
      image_tag('default.jpg', height: '230', width: '230')
    when '7-Eleven brand gasoline'
      image_tag('711.png', height: '230', width: '230')
    when '76'
      image_tag('76.png', height: '230', width: '230')
    when 'Sam\'s Club'
      image_tag('samsclub.png', height: '230', width: '230')
    when 'Sheetz'
      image_tag('default.jpg', height: '230', width: '230')
    when 'Sinclair'
      image_tag('default.jpg', height: '230', width: '230')
    when 'Speedway'
      image_tag('speedway.png', height: '230', width: '230')
    when 'Spinx'
      image_tag('default.jpg', height: '230', width: '230')
    when 'Sunoco'
      image_tag('sunoco.png', height: '230', width: '230')
    when 'Texaco'
      image_tag('texaco.png', height: '230', width: '230')
    when 'Travelcenters of America'
      image_tag('default.jpg', height: '230', width: '230')
    when 'Valero'
      image_tag('valero.png', height: '230', width: '230')
    when 'Wawa'
      image_tag('wawa.jpg', height: '230', width: '230')
    else
      image_tag('default.jpg', height: '230', width: '230')
    end
  end
end

app/views/retailers/_my_stations.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <div class='page-header'>
      <h1 class='pull-left'>
        <i class='icon-beer'></i>
        <span>Your Stations</span>
      </h1>
    </div>
    <div class="dash-tool">
      <div class="btn-group" role="group" id="dash_tool" aria-label="...">
        <button type="button" class="btn btn-default"><%= link_to "My stations", retailer_my_stations_path %></button>
        <button type="button" class="btn btn-default"><%= link_to "Inactive Stations", retailer_inactive_stations_path %></button>
        <button type="button" class="btn btn-default"><%= link_to "Transfers", retailer_transfers_path %></button>
        <button type="button" class="btn btn-default"><%= link_to new_station_path do %>
          <i class='icon-plus'></i>
          Add Station</span>
        <% end %></button>

    </div>
  </div>
</div>
</div>

app/views/retailers/dashboard.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <div class='page-header'>
      <h1 class='pull-left'>
        <i class='icon-dashboard'></i>
        <span><%=current_user.first_name%>'s Dashboard</span>
      </h1>
    </div>
  </div>
</div>

app/views/retailers/inactive_stations.html.erb
<%= render "my_stations"%>

<h1>
  You dont have any inactive stations
</h1>

app/views/retailers/my_stations.html.erb
<%= render "my_stations"%>

<% @stations.each do |station| %>
<div class="station box" style="margin-bottom: 0">
  <div class="box-header dark-background">
    <div class="title"><%= station.brand + " " + "@" + " " + station.city + " " + "-" + station.zip%></div>
    <div class="actions">
      <%=link_to station_path(station) do %>
      <span class="btn btn-danger">View Station</span>
      <%end%>
    </div>
  </div>
  <div class="box-content">
    <div class="station-image"><%= image_for(station)%></div>
    <div class="station-data">
      <div class="box bordered-box blue-border" style="margin-bottom:0;">
        <div class="box-header grey-background">
          <div class="title">
            <i class="icon-truck"></i>Recent Orders</div>
        </div>
        <div class="box-content box-no-padding">
          <div class="responsive-table">
            <table class="table" style="margin-bottom:0;">
              <thead>
                <tr>
                  <th>
                    Fuel Type
                  </th>
                  <th>
                    Supplier
                  </th>
                  <th>
                    Status
                  </th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Regular</td>
                  <td>JK Petroleum</td>
                  <td>
                    <span class="label label-important">Warning</span>
                  </td>
                  <td>
                    <div class="text-right">
                      <a class="btn btn-xs" href="#">
                        <i class="icon-edit">
                          View/Edit</i>
                      </a>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td>Diesel</td>
                  <td>ACME Petroleum</td>
                  <td>
                    <span class="label label-success">Success</span>
                  </td>
                  <td>
                    <div class="text-right">
                      <a class="btn btn-xs" href="#">
                        <i class="icon-edit">
                          View/Edit</i>
                      </a>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td>Supreme</td>
                  <td>Jerry Petroleum</td>
                  <td>
                    <span class="label label-warning">Pending</span>
                  </td>
                  <td>
                    <div class="text-right">
                      <a class="btn  btn-xs" href="#">
                        <i class="icon-edit">
                          View/Edit</i>
                      </a>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr class="hr-drouble">
  <%end%>

app/views/retailers/transfers.html.erb
<%= render "my_stations"%>

<h1>
  You dont have any Transfers
</h1>