config/routes.rb
Rails.application.routes.draw do
  resources :stations do
    resources :tanks
  end
  resources :retailer_suppliers

  devise_for :users, skip: [:registration]
  devise_for :retailers
  devise_for :suppliers
  devise_for :admins, skip: [:registration]
  get 'retailer_suppliers/pending' => 'retailer_suppliers#pending'
  get 'pages/about'
  get 'pages/contact'
  get 'retailer/transfers' => 'retailers#transfers'
  get 'retailer/inactive_stations' => 'retailers#inactive_stations'
  get 'retailer/dashboard' => 'retailers#dashboard', as: :retailer_dashboard
  get 'admin/dashboard' => 'admins#dashboard', as: :admin_dashboard
  get 'supplier/dashboard' => 'suppliers#dashboard', as: :supplier_dashboard
  get 'retailer/my_stations' => 'retailers#my_stations'
  get 'admin/retailers' => 'admins#retailers'

  root to: 'pages#home'
end

app/views/layouts/_admin_sidebar.html.erb
<div id="wrapper">
  <div id='main-nav-bg'></div>
  <nav class='main-nav-fixed' id='main-nav'>
    <div class='navigation'>
      <ul class='nav nav-stacked'>
        <li class=''>
          <%= link_to retailer_dashboard_path do %>
          <i class='icon-tasks'></i>
          <span class="text-error">
            <strong><%=current_admin.account_number%></strong>
          </span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to admin_retailers_path do %>
          <i class='icon-beer'></i>
          <span>Retailers</span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-truck'></i>
          <span>My Orders</span>
          <% end %>
        </li>

        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-group'></i>
          <span>My Suppliers</span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-folder-open'></i>
          <span>My Documents</span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-bar-chart'></i>
          <span>Reports</span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-file-text'></i>
          <span>My Invoices</span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <% if user_signed_in? && current_user.retailer?%>
    <a class="navbar-brand" href="/retailer/dashboard">Petrohub</a>
    <% elsif user_signed_in? && current_user.supplier?%>
    <a class="navbar-brand" href="/supplier/dashboard">Petrohub</a>
    <% elsif user_signed_in? && current_user.admin? %>
    <a class="navbar-brand" href="/admin/dashboard">Petrohub</a>
  <% else %>
    <a class="navbar-brand" href="/">Petrohub</a>
    <%end%>
  </div>
  <% if user_signed_in? %>
  <a class='toggle-nav btn pull-left' href='#'>
    <i class='icon-reorder'></i>
  </a>
  <%end%>
  <ul class="nav">

    <% if user_signed_in? && current_user.retailer? %>
    <li>
      <a href="#">Profile</a>
    </li>
    <li><%= link_to "Account Settings", edit_retailer_registration_path %></li>
    <li><%= link_to "Log Out", destroy_user_session_path,method: :delete%></li>
    <% elsif user_signed_in? && current_user.supplier? %>
    <li>
      <a href="#">Profile</a>
    </li>
    <li><%= link_to "Account Settings", edit_supplier_registration_path %></li>
    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    <%else%>
    <li><%= link_to "About", pages_about_path %></li>
    <li><%= link_to "Contact Us",pages_contact_path%></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign Up
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Retailer", new_retailer_registration_path %></li>
        <li><%= link_to "Supplier", new_supplier_registration_path %></li>
      </ul>
    </li>
    <li><%= link_to "Sign In", user_session_path %></li>
  </li>
  <% end %>

</ul>
</nav>

app/views/layouts/_retailer_sidebar.html.erb
<div id="wrapper">
  <div id='main-nav-bg'></div>
  <nav class='main-nav-fixed' id='main-nav'>
    <div class='navigation'>
      <ul class='nav nav-stacked'>
        <li class=''>
          <%= link_to retailer_dashboard_path do %>
          <i class='icon-tasks'></i>
          <span class="text-error">
            <strong><%=current_user.account_number%></strong>
          </span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-beer'></i>
          <span>My Stations</span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-truck'></i>
          <span>My Orders</span>
          <% end %>
        </li>

        <li class=''>
          <%= link_to retailer_suppliers_path do %>
          <i class='icon-group'></i>
          <span>My Suppliers</span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-folder-open'></i>
          <span>My Documents</span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-bar-chart'></i>
          <span>Reports</span>
          <% end %>
        </li>
        <li class=''>
          <%= link_to retailer_my_stations_path do %>
          <i class='icon-file-text'></i>
          <span>My Invoices</span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_supplier_sidebar.html.erb
<div id="wrapper">
  <div id='main-nav-bg'></div>
  <nav class='main-nav-fixed' id='main-nav'>
    <div class='navigation'>
      <ul class='nav nav-stacked'>
        <li class=''>
          <%= link_to supplier_dashboard_path do %>
          <i class='icon-tasks'></i>
          <span class="text-error">
            <strong><%=current_user.account_number%></strong>
          </span>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Petrohub</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='contrast-dark'>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <%= render 'layouts/retailer_sidebar' if user_signed_in? && current_user.retailer?%>
    <%= render 'layouts/supplier_sidebar' if user_signed_in? && current_user.supplier?%>
    <%= render 'layouts/admin_sidebar' if user_signed_in? && current_user.admin?%>
    <section id='content'>
      <div class='container'>
        <div class='row' id='content-wrapper'>
          <div class='col-xs-12'>
            <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-info") %>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </section>
    </div>

  </div>
</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Petrohub</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='contrast-dark'>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <div class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>